spring:
  profiles:
    default: local
    group:
      local: thymeleaf-local, datasource-local, h2db-local, email-local, oauth-local, jpa-local, server-local, image-bucket-local, redis-local
      prod: thymeleaf-prod, datasource-prod, mysql-prod, email-prod, oauth-prod, jpa-prod, server-prod, image-bucket-prod, redis-prod
