spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: validate
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true

    locations:
      - classpath:db/migration/mysql
