spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE_NAME}?useSSL=false
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
