spring:
  profiles:
    default: local
    group:
      local: thymeleaf-local, datasource-local, h2db-local, email-local, oauth-local, jpa-local, server-local, image-bucket-local
      prod: thymeleaf-prod
