-- AGENT
CREATE TABLE IF NOT EXISTS `AGENT` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `EMAIL` VARCHAR(255) UNIQUE NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `NICKNAME` VARCHAR(255) UNIQUE NOT NULL,

    `PROFILE_IMAGE` VARCHAR(255),
    `INTRODUCTION` TEXT
);

CREATE INDEX `IDX_AGENT` ON `AGENT` (`EMAIL`);

-- NOTICE
CREATE TABLE IF NOT EXISTS `NOTICE` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `WRITER_ID` BIGINT,
    `CONTENT` TEXT,
    `IMAGE_URI` VARCHAR(255)
);

CREATE INDEX `IDX_NOTICE` ON `NOTICE` (`WRITER_ID`);

-- NOTIFIED_PANEL
CREATE TABLE IF NOT EXISTS `NOTIFIED_PANEL` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `PANEL_ID` BIGINT,
    `NOTICE_ID` BIGINT
);

CREATE INDEX `IDX_NOTIFIED_PANEL` ON `NOTIFIED_PANEL` (`NOTICE_ID`, `PANEL_ID`);

-- PANEL
CREATE TABLE IF NOT EXISTS `PANEL` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `AGENT_ID` BIGINT,
    `PROVIDER` VARCHAR(15),
    `PRINCIPAL_NAME` VARCHAR(255),
    `DESCRIPTION` TEXT,
    `ACCOUNT` VARCHAR(255),
    `LOCATION` INT
);

CREATE INDEX `IDX_PANEL` ON `PANEL` (`AGENT_ID`);

-- REFRESH_TOKEN
CREATE TABLE IF NOT EXISTS `REFRESH_TOKEN` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `PROVIDER` VARCHAR(15),
    `PRINCIPAL_NAME` VARCHAR(255),

    `TOKEN` TEXT,
    `ISSUED_AT` TIMESTAMP,
    `EXPIRES_AT` TIMESTAMP
);

CREATE INDEX `IDX_REFRESH_TOKEN` ON `REFRESH_TOKEN` (`PROVIDER`, `PRINCIPAL_NAME`);

-- ROLE_OF_AGENT
CREATE TABLE IF NOT EXISTS `ROLE_OF_AGENT` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `AGENT_ID` BIGINT,
    `ROLE` VARCHAR(15)
);

CREATE INDEX `IDX_ROLE_OF_AGENT` ON `ROLE_OF_AGENT` (`AGENT_ID`, `ROLE`);

-- FOREIGN KEYS
ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_NOTICE_WRITER`
FOREIGN KEY (`WRITER_ID`)
REFERENCES `AGENT` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `NOTIFIED_PANEL` ADD CONSTRAINT `FK_NOTIFIED_PANEL_PANEL`
FOREIGN KEY (`PANEL_ID`)
REFERENCES `PANEL` (`ID`);

ALTER TABLE `NOTIFIED_PANEL` ADD CONSTRAINT `FK_NOTIFIED_PANEL_NOTICE`
FOREIGN KEY (`NOTICE_ID`)
REFERENCES `NOTICE` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `PANEL` ADD CONSTRAINT `FK_PANEL_AGENT`
FOREIGN KEY (`AGENT_ID`)
REFERENCES `AGENT` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `ROLE_OF_AGENT` ADD CONSTRAINT `FK_ROLE_OF_AGENT_AGENT`
FOREIGN KEY (`AGENT_ID`)
REFERENCES `AGENT` (`ID`)
ON DELETE CASCADE
ON UPDATE CASCADE;
