-- AGENT
CREATE TABLE IF NOT EXISTS `agent` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `EMAIL` VARCHAR(255) UNIQUE NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `NICKNAME` VARCHAR(255) UNIQUE NOT NULL,

    `PROFILE_IMAGE` VARCHAR(255),
    `INTRODUCTION` TEXT
);

CREATE INDEX `IDX_AGENT` ON `agent` (`EMAIL`);

-- NOTICE
CREATE TABLE IF NOT EXISTS `notice` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `WRITER_ID` BIGINT,
    `CONTENT` TEXT,
    `IMAGE_URI` VARCHAR(255)
);

CREATE INDEX `IDX_NOTICE` ON `notice` (`WRITER_ID`);

-- NOTIFIED_PANEL
CREATE TABLE IF NOT EXISTS `notified_panel` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `PANEL_ID` BIGINT,
    `NOTICE_ID` BIGINT
);

CREATE INDEX `IDX_NOTIFIED_PANEL` ON `notified_panel` (`NOTICE_ID`, `PANEL_ID`);

-- PANEL
CREATE TABLE IF NOT EXISTS `panel` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `AGENT_ID` BIGINT,
    `PROVIDER` VARCHAR(15),
    `PRINCIPAL_NAME` VARCHAR(255),
    `DESCRIPTION` TEXT,
    `ACCOUNT` VARCHAR(255),
    `LOCATION` INT
);

CREATE INDEX `IDX_PANEL` ON `panel` (`AGENT_ID`);

-- REFRESH_TOKEN
CREATE TABLE IF NOT EXISTS `refresh_token` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `PROVIDER` VARCHAR(15),
    `PRINCIPAL_NAME` VARCHAR(255),

    `TOKEN` TEXT,
    `ISSUED_AT` TIMESTAMP,
    `EXPIRES_AT` TIMESTAMP
);

CREATE INDEX `IDX_REFRESH_TOKEN` ON `refresh_token` (`PROVIDER`, `PRINCIPAL_NAME`);

-- ROLE_OF_AGENT
CREATE TABLE IF NOT EXISTS `role_of_agent` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CREATED_AT` TIMESTAMP,

    `AGENT_ID` BIGINT,
    `ROLE` VARCHAR(15)
);

CREATE INDEX `IDX_ROLE_OF_AGENT` ON `role_of_agent` (`AGENT_ID`, `ROLE`);

-- FOREIGN KEYS
ALTER TABLE `notice` ADD CONSTRAINT `FK_NOTICE_WRITER`
FOREIGN KEY (`WRITER_ID`)
REFERENCES `agent` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `notified_panel` ADD CONSTRAINT `FK_NOTIFIED_PANEL_PANEL`
FOREIGN KEY (`PANEL_ID`)
REFERENCES `panel` (`ID`);

ALTER TABLE `notified_panel` ADD CONSTRAINT `FK_NOTIFIED_PANEL_NOTICE`
FOREIGN KEY (`NOTICE_ID`)
REFERENCES `notice` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `panel` ADD CONSTRAINT `FK_PANEL_AGENT`
FOREIGN KEY (`AGENT_ID`)
REFERENCES `agent` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `role_of_agent` ADD CONSTRAINT `FK_ROLE_OF_AGENT_AGENT`
FOREIGN KEY (`AGENT_ID`)
REFERENCES `agent` (`ID`)
ON DELETE CASCADE
ON UPDATE CASCADE;
